<?php
error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED);

include_once(dirname(__FILE__) . '/../../../../Services/Autoloader/fabAutoloader.php');
require_once dirname(__FILE__) . '/../../../../../../../c_libraries/lw/lw_object.class.php';
require_once dirname(__FILE__) . '/../../../../../../../c_libraries/lw/lw_db.class.php';
require_once dirname(__FILE__) . '/../../../../../../../c_libraries/lw/lw_db_mysqli.class.php';
require_once dirname(__FILE__) . '/../../../../../../../c_libraries/lw/lw_registry.class.php';
require_once dirname(__FILE__) . '/../../../Config/phpUnitConfig.php';

/**
 * Test class for eventValidate.
 * Generated by PHPUnit on 2013-01-03 at 11:48:05.
 */
class countryCommandHandlerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var eventValidate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $phpUnitConfig = new phpUnitConfig();
        $config = $phpUnitConfig->getConfig();
        
        $db = new lw_db_mysqli($config["lwdb"]["user"], $config["lwdb"]["pass"], $config["lwdb"]["host"], $config["lwdb"]["db"]);
        $db->connect();
        $this->db = $db;
        
        $autoloader = new Fab\Service\Autoloader\fabAutoloader();
        $autoloader->setConfig(array("plugins" => $config["plugins"],
                                     "plugin_path" => array ("lw" => $config["plugin_path"]["lw"] )));
        
        $this->countryCommandHandler = new Fab\Domain\Country\Model\countryCommandHandler($this->db);
        $this->countryCommandHandler->setDebug(false);  
        
        $this->assertTrue($this->countryCommandHandler->createTable());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->db->setStatement("DROP TABLE t:fab_laender ");
        $this->db->pdbquery();
    }

    /**
     * @todo Implement test().
     */
    public function testCreateTable()
    {
        $this->tearDown();
        
        $this->assertTrue($this->countryCommandHandler->createTable());
        $this->assertTrue($this->db->tableExists($this->db->gt("fab_laender")));
    }
    
    public function testImportCountries()
    {
        $this->assertTrue($this->countryCommandHandler->importCountries());
        
        $data = array();
        $file = fopen( dirname(__FILE__)."/../../../../Domain/Country/Model/data/countries.csv", 'r');
        while (($line = fgetcsv($file,100,";")) !== FALSE) {
            array_push($data, $line);
        }
        fclose($file);

        $assertedArray = array();
        foreach ($data as $value) {
            array_push($assertedArray,array("land" => $value[0], "bezeichnung" => $value[1]));
        }
        
        foreach ($assertedArray as $key => $value) {
            $land[$key] = strtolower($value["land"]);
        }
        array_multisort($land, SORT_ASC, $assertedArray);
        
        $this->db->setStatement("SELECT * FROM t:fab_laender ");
        $result = $this->db->pselect();
        
        $this->assertEquals($assertedArray, $result);
    }
}